# 🚀 NumPy Fundamentals: A Cool Journey Through Numerical Computing

Welcome to this comprehensive guide to NumPy! We'll explore the fundamental concepts with practical examples that showcase the power of numerical computing in Python.

## What is NumPy?
NumPy (Numerical Python) is the foundation of scientific computing in Python. It provides:
- Powerful N-dimensional array objects
- Broadcasting functions
- Linear algebra operations
- Random number generation
- And much more!

In [1]:
# Let's start by importing NumPy
import numpy as np
import matplotlib.pyplot as plt
import time

print(f"NumPy version: {np.__version__}")
print("🎉 Ready to explore NumPy!")

NumPy version: 2.3.1
🎉 Ready to explore NumPy!


## 1. 📊 Creating Arrays - The Foundation

Arrays are the heart of NumPy. Let's explore different ways to create them!

In [3]:
# Creating arrays from lists
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:", arr_1d)
print("\n2D Array:")
print(arr_2d)
print("\n3D Array:")
print(arr_3d)

print(f"\n📏 Shapes: 1D: {arr_1d.shape}, 2D: {arr_2d.shape}, 3D: {arr_3d.shape}")

1D Array: [1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

📏 Shapes: 1D: (5,), 2D: (3, 3), 3D: (2, 2, 2)


In [4]:
# Cool array creation functions
zeros = np.zeros((3, 4))
ones = np.ones((2, 3, 4))
full_array = np.full((3, 3), 7)
identity = np.eye(4)
random_array = np.random.random((3, 3))

print("🔢 Zeros array:")
print(zeros)
print("\n🎯 Identity matrix:")
print(identity)
print("\n🎲 Random array:")
print(random_array)

🔢 Zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

🎯 Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

🎲 Random array:
[[0.06980352 0.35899895 0.15447775]
 [0.36629534 0.43878406 0.12114824]
 [0.47008367 0.80116837 0.44053337]]


In [ ]:
# Range and spacing functions
range_array = np.arange(0, 20, 2)  # start, stop, step
linspace_array = np.linspace(0, 10, 5)  # start, stop, num_points
logspace_array = np.logspace(0, 2, 5)  # 10^0 to 10^2, 5 points

print("📈 Range array (0 to 20, step 2):", range_array)
print("📏 Linspace array (0 to 10, 5 points):", linspace_array)
print("📊 Logspace array (10^0 to 10^2, 5 points):", logspace_array)

## 2. 🔍 Array Inspection and Properties

Understanding your arrays is crucial!

In [ ]:
# Create a sample array for inspection
sample_array = np.random.randint(1, 100, size=(4, 5))

print("🔬 Sample Array:")
print(sample_array)
print(f"\n📏 Shape: {sample_array.shape}")
print(f"📐 Dimensions: {sample_array.ndim}")
print(f"📊 Size (total elements): {sample_array.size}")
print(f"🏷️ Data type: {sample_array.dtype}")
print(f"💾 Memory usage: {sample_array.nbytes} bytes")
print(f"📋 Item size: {sample_array.itemsize} bytes per element")

## 3. ✂️ Array Indexing and Slicing

Accessing and modifying array elements like a pro!

In [ ]:
# Create a sample 2D array
matrix = np.arange(20).reshape(4, 5)
print("🎯 Original Matrix:")
print(matrix)

# Basic indexing
print(f"\n🔍 Element at [2, 3]: {matrix[2, 3]}")
print(f"🔍 First row: {matrix[0, :]}")
print(f"🔍 Last column: {matrix[:, -1]}")

# Advanced slicing
print("\n✂️ Submatrix [1:3, 2:4]:")
print(matrix[1:3, 2:4])

# Boolean indexing
mask = matrix > 10
print(f"\n🎭 Elements > 10: {matrix[mask]}")

# Fancy indexing
rows = [0, 2, 3]
cols = [1, 3, 4]
print(f"\n✨ Fancy indexing [rows={rows}, cols={cols}]: {matrix[rows, cols]}")

## 4. 🧮 Mathematical Operations

NumPy makes math operations blazingly fast!

In [ ]:
# Element-wise operations
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("🔢 Array a:", a)
print("🔢 Array b:", b)
print(f"\n➕ Addition: {a + b}")
print(f"➖ Subtraction: {a - b}")
print(f"✖️ Multiplication: {a * b}")
print(f"➗ Division: {a / b}")
print(f"🔺 Power: {a ** 2}")
print(f"🌊 Square root: {np.sqrt(a)}")
print(f"📐 Sine: {np.sin(a)}")
print(f"📊 Exponential: {np.exp(a)}")

In [ ]:
# Statistical operations
data = np.random.normal(50, 15, 1000)  # Normal distribution: mean=50, std=15

print("📊 Statistical Analysis of Random Data:")
print(f"📈 Mean: {np.mean(data):.2f}")
print(f"📊 Median: {np.median(data):.2f}")
print(f"📏 Standard Deviation: {np.std(data):.2f}")
print(f"📋 Variance: {np.var(data):.2f}")
print(f"🔺 Maximum: {np.max(data):.2f}")
print(f"🔻 Minimum: {np.min(data):.2f}")
print(f"📐 25th Percentile: {np.percentile(data, 25):.2f}")
print(f"📐 75th Percentile: {np.percentile(data, 75):.2f}")

## 5. 🎭 Broadcasting - NumPy's Superpower

Broadcasting allows operations on arrays of different shapes!

In [ ]:
# Broadcasting examples
matrix = np.arange(12).reshape(3, 4)
row_vector = np.array([1, 2, 3, 4])
col_vector = np.array([[10], [20], [30]])
scalar = 100

print("🎭 Broadcasting Examples:")
print("\nOriginal matrix:")
print(matrix)
print(f"Matrix shape: {matrix.shape}")

print(f"\nRow vector: {row_vector} (shape: {row_vector.shape})")
print("Matrix + Row vector:")
print(matrix + row_vector)

print(f"\nColumn vector: {col_vector.ravel()} (shape: {col_vector.shape})")
print("Matrix + Column vector:")
print(matrix + col_vector)

print(f"\nScalar: {scalar}")
print("Matrix * Scalar:")
print(matrix * scalar)

## 6. 🔄 Array Manipulation

Reshaping, splitting, and joining arrays!

In [ ]:
# Reshaping arrays
original = np.arange(24)
print("🔄 Array Reshaping:")
print(f"Original array: {original}")
print(f"Shape: {original.shape}")

# Different reshape options
reshaped_2d = original.reshape(4, 6)
reshaped_3d = original.reshape(2, 3, 4)

print("\n📊 Reshaped to 4x6:")
print(reshaped_2d)
print("\n📦 Reshaped to 2x3x4:")
print(reshaped_3d)

# Flattening
flattened = reshaped_2d.flatten()
print(f"\n🌊 Flattened back: {flattened}")

In [ ]:
# Joining and splitting arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("🔗 Joining Arrays:")
print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)

# Concatenation
h_concat = np.hstack([arr1, arr2])  # Horizontal
v_concat = np.vstack([arr1, arr2])  # Vertical

print("\n↔️ Horizontal concatenation:")
print(h_concat)
print("\n↕️ Vertical concatenation:")
print(v_concat)

# Splitting
print("\n✂️ Splitting the horizontal concatenation:")
split_arrays = np.hsplit(h_concat, 2)
print("First part:", split_arrays[0])
print("Second part:", split_arrays[1])

## 7. 🎲 Random Numbers and Simulations

NumPy's random module is perfect for simulations and statistical analysis!

In [ ]:
# Set seed for reproducibility
np.random.seed(42)

print("🎲 Random Number Generation:")

# Different distributions
uniform = np.random.uniform(0, 1, 10)
normal = np.random.normal(0, 1, 10)
integers = np.random.randint(1, 100, 10)
choice = np.random.choice(['A', 'B', 'C', 'D'], 10)

print(f"🎯 Uniform [0,1]: {uniform[:5]}...")  # Show first 5
print(f"📊 Normal (μ=0, σ=1): {normal[:5]}...")
print(f"🔢 Random integers [1,100): {integers[:5]}...")
print(f"🎪 Random choice: {choice[:5]}...")

# Shuffle an array
deck = np.arange(1, 53)  # Card deck
np.random.shuffle(deck)
print(f"\n🃏 Shuffled deck (first 10): {deck[:10]}")

In [ ]:
# Monte Carlo simulation: Estimating π
print("🎯 Monte Carlo Simulation: Estimating π")

n_points = 100000
x = np.random.uniform(-1, 1, n_points)
y = np.random.uniform(-1, 1, n_points)

# Points inside unit circle
inside_circle = (x**2 + y**2) <= 1
pi_estimate = 4 * np.sum(inside_circle) / n_points

print(f"🔢 Number of points: {n_points:,}")
print(f"🎯 Points inside circle: {np.sum(inside_circle):,}")
print(f"🥧 Estimated π: {pi_estimate:.6f}")
print(f"📊 Actual π: {np.pi:.6f}")
print(f"❌ Error: {abs(pi_estimate - np.pi):.6f}")

## 8. 🧊 Linear Algebra with NumPy

Powerful linear algebra operations made simple!

In [ ]:
# Matrix operations
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
v = np.array([1, 2, 3])

print("🧊 Linear Algebra Operations:")
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print(f"\nVector v: {v}")

# Matrix multiplication
matrix_mult = np.dot(A, B)  # or A @ B
print("\n✖️ Matrix multiplication A @ B:")
print(matrix_mult)

# Matrix-vector multiplication
mv_mult = np.dot(A, v)
print(f"\n🎯 Matrix-vector multiplication A @ v: {mv_mult}")

# Transpose
print("\n🔄 Transpose of A:")
print(A.T)

In [ ]:
# Advanced linear algebra
# Create a well-conditioned matrix
C = np.array([[4, 2, 1], [2, 5, 3], [1, 3, 6]])

print("🔬 Advanced Linear Algebra:")
print("Matrix C:")
print(C)

# Determinant
det_C = np.linalg.det(C)
print(f"\n🎯 Determinant: {det_C:.2f}")

# Inverse
if det_C != 0:
    inv_C = np.linalg.inv(C)
    print("\n🔄 Inverse matrix:")
    print(inv_C)
    
    # Verify: C @ inv(C) should be identity
    identity_check = np.dot(C, inv_C)
    print("\n✅ Verification C @ inv(C):")
    print(np.round(identity_check, 10))  # Round to avoid floating point errors

# Eigenvalues and eigenvectors
eigenvals, eigenvecs = np.linalg.eig(C)
print(f"\n🌟 Eigenvalues: {eigenvals}")
print("\n🎭 Eigenvectors:")
print(eigenvecs)

## 9. ⚡ Performance Comparison

See why NumPy is so much faster than pure Python!

In [ ]:
# Performance comparison: NumPy vs Pure Python
size = 1000000

# Create data
python_list = list(range(size))
numpy_array = np.arange(size)

print("⚡ Performance Comparison: Sum of 1 million numbers")
print(f"📊 Data size: {size:,} elements")

# Pure Python timing
start_time = time.time()
python_sum = sum(python_list)
python_time = time.time() - start_time

# NumPy timing
start_time = time.time()
numpy_sum = np.sum(numpy_array)
numpy_time = time.time() - start_time

print(f"\n🐍 Pure Python time: {python_time:.6f} seconds")
print(f"🚀 NumPy time: {numpy_time:.6f} seconds")
print(f"⚡ NumPy is {python_time/numpy_time:.1f}x faster!")
print(f"✅ Results match: {python_sum == numpy_sum}")

## 10. 📈 Practical Example: Data Analysis

Let's analyze some simulated sales data!

In [ ]:
# Simulate sales data for a year
np.random.seed(123)

# Generate daily sales for 365 days
base_sales = 1000
trend = np.linspace(0, 200, 365)  # Growing trend
seasonality = 100 * np.sin(2 * np.pi * np.arange(365) / 365)  # Yearly cycle
noise = np.random.normal(0, 50, 365)  # Random variation

daily_sales = base_sales + trend + seasonality + noise
daily_sales = np.maximum(daily_sales, 0)  # Ensure non-negative sales

print("📈 Sales Data Analysis")
print(f"📊 Total days: {len(daily_sales)}")
print(f"💰 Average daily sales: ${np.mean(daily_sales):.2f}")
print(f"📈 Total annual sales: ${np.sum(daily_sales):,.2f}")
print(f"🔺 Highest daily sales: ${np.max(daily_sales):.2f}")
print(f"🔻 Lowest daily sales: ${np.min(daily_sales):.2f}")
print(f"📏 Standard deviation: ${np.std(daily_sales):.2f}")

# Monthly analysis
monthly_sales = daily_sales.reshape(12, -1)  # Approximate months
monthly_avg = np.mean(monthly_sales, axis=1)

print("\n📅 Monthly Analysis:")
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

for i, month in enumerate(months):
    print(f"{month}: ${monthly_avg[i]:.2f}")

best_month = months[np.argmax(monthly_avg)]
worst_month = months[np.argmin(monthly_avg)]
print(f"\n🏆 Best month: {best_month}")
print(f"📉 Worst month: {worst_month}")

In [ ]:
# Create a simple visualization
plt.figure(figsize=(12, 6))
plt.plot(daily_sales, alpha=0.7, linewidth=1, label='Daily Sales')
plt.plot(np.convolve(daily_sales, np.ones(30)/30, mode='valid'), 
         color='red', linewidth=2, label='30-day Moving Average')

plt.title('📈 Daily Sales Throughout the Year', fontsize=16, fontweight='bold')
plt.xlabel('Day of Year')
plt.ylabel('Sales ($)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

print("🎉 Visualization complete! The red line shows the 30-day moving average.")

## 🎓 Key Takeaways

Congratulations! You've learned the fundamentals of NumPy:

1. **🏗️ Array Creation**: Various ways to create and initialize arrays
2. **🔍 Array Properties**: Understanding shape, size, and data types
3. **✂️ Indexing & Slicing**: Accessing and modifying array elements
4. **🧮 Mathematical Operations**: Element-wise and statistical operations
5. **🎭 Broadcasting**: Operations on arrays of different shapes
6. **🔄 Array Manipulation**: Reshaping, joining, and splitting
7. **🎲 Random Numbers**: Generating random data and simulations
8. **🧊 Linear Algebra**: Matrix operations and decompositions
9. **⚡ Performance**: Why NumPy is faster than pure Python
10. **📈 Practical Applications**: Real-world data analysis

## 🚀 Next Steps

- Explore **Pandas** for data manipulation
- Learn **Matplotlib/Seaborn** for advanced visualization
- Dive into **SciPy** for scientific computing
- Try **Scikit-learn** for machine learning

Happy coding! 🐍✨